//MIAUSEproject-founderKJ/multi-platform-AI/core/platform/boot_sequence.go

package platform

import (
	"fmt"

	"time"

	"github.com/MIAUSEproject-founderKJ/multi-platform-AI/internal/schema"
)

// BootSequence represents the final "Clearance Report" generated by the BootManager.
// It is the immutable contract handed over to the AIOS Kernel.
type BootSequence struct {
	// Identity
	PlatformID schema.PlatformClass `json:"platform_id"`
	HardwareID string               `json:"hardware_id"`

	// Trust & Security
	TrustScore float64 `json:"trust_score"` // 0.0 to 1.0
	IsVerified bool    `json:"is_verified"` // True if binary attestation passed

	// Operational Constraints
	Mode     string `json:"mode"`      // "AUTONOMOUS", "ASSISTED", "MANUAL_ONLY"
	UserRole string `json:"user_role"` // "Admin", "Operator", "Guest"

	// Metadata
	BootTime  time.Duration `json:"boot_duration"`
	Timestamp time.Time     `json:"timestamp"`
}

// Summary returns a human-readable log line for the console.
func (bs *BootSequence) Summary() string {
	return fmt.Sprintf("[%s] Booted as %s | Trust: %.0f%% | Mode: %s",
		bs.Timestamp.Format("15:04:05"),
		bs.PlatformID,
		bs.TrustScore*100,
		bs.Mode,
	)
}

// CanOperate returns true if the system allows any form of actuation.
func (bs *BootSequence) CanOperate() bool {
	return bs.Mode != "MANUAL_ONLY"
}

// IsAutonomous returns true only if the trust is high enough for self-governance.
func (bs *BootSequence) IsAutonomous() bool {
	return bs.Mode == "AUTONOMOUS"
}
